### ISSUE TITLE
Wrong pinout for XC95144PQ100 ?

### ISSUE THREAD

**Issue by jbtronics** [KiCad/kicad-library#217] opened 2015-06-07 10:47 UTC
I wanted to use the Symbol of XC95144PQ100 for a project.
But when I has compared the Symbol with the pinout mentioned in the Datasheet of this (http://www.xilinx.com/support/documentation/data_sheets/ds056.pdf), all Pins are on other Positions.
Is these desired or a bug?

**Comment by keruseykaryu** [comment] 2015-06-07 11:41
This is an old Xlinix library and might be buggy. Almost all KiCad libraries was designed and created by its users. So I don't know the intentions of the author of this symbol. I don't wanna guess.

I will mark this as bug, because the pins indeed doesn't match. If you can fix this issue, please do so and create pull request.
Because this is the CPLD series device, I hope any updates will not be in conflict with **Alex's** work **https://github.com/KiCad/kicad-library/pull/170**

**Comment by ricardocrudo** [comment] 2015-07-24 20:51
@do9jhb the right datasheet for XC95144PQ100 is: http://www.xilinx.com/support/documentation/data_sheets/ds067.pdf

**Comment by Shackmeister** [comment] 2017-07-01 03:52
@jbtronics Im not really sure if this relevant anymore, could you please consider closing this issue if not?

**Comment by bobc** [comment] 2017-07-05 09:14
The confusion here is that XC95144 is an old (obsolete) series, the new series is named XC95144XL, but Xilinx did not keep pin compatibility between the  old and new series.

Ideally, the obsolete versions should be tagged "obsolete - use XL for new designs" or something.

**Comment by SchrodingersGat** [comment] 2017-07-05 09:38
@jbtronics I know this is a long time since you raised this issue but would you be willing to contribute a fix? :)

**Comment by bobc** [comment] 2017-07-05 10:20
I believe there is nothing that really needs fixing here. The OP simply got confused by similar named but different parts. The "bug" label is incorrect, there is no bug. https://github.com/KiCad/kicad-library/pull/218 is incorrect and should NOT be applied.

I just did a partial check and the current symbols appear to be correct (XC95144PQ100 and XC95144XL-TQ100), if you look at the right datasheets.

**Comment by SchrodingersGat** [comment] 2017-07-05 10:28
Right, thanks for the investigation @bobc

**Closed** 2017-09-15 06:44 UTC
Labels: bug
